import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Labial "Lunáticas"',
    description: 'Nuestro labial insignia con un acabado mate aterciopelado de larga duración. Color intenso en una sola pasada.',
    price: 45.9,
    category: 'Maquillaje',
    keywords: 'labial, mate, belleza, maquillaje',
    imageId: 'product-1',
  },
  {
    id: '2',
    name: 'Base de Maquillaje "Piel Perfecta"',
    description: 'Cobertura media a completa con un acabado natural y luminoso. Unifica el tono de la piel y dura todo el día.',
    price: 79.9,
    category: 'Maquillaje',
    keywords: 'base, maquillaje, rostro, belleza',
    imageId: 'product-2',
  },
  {
    id: '3',
    name: 'Paleta de Sombras "Ojos de Gato"',
    description: 'Una selección de 12 sombras de alta pigmentación en tonos neutros y audaces para crear looks ilimitados.',
    price: 99.0,
    category: 'Maquillaje',
    keywords: 'sombras, ojos, paleta, maquillaje',
    imageId: 'product-3',
  },
  {
    id: '4',
    name: 'Set de Collares "Dorado Chic"',
    description: 'Combina tus looks con este set de collares en tendencia. Piezas únicas y ligeras para realzar tu estilo.',
    price: 59.9,
    originalPrice: 99.9,
    category: 'Accesorios',
    keywords: 'collares, dorado, accesorios, moda',
    imageId: 'product-7',
  },
  {
    id: '5',
    name: 'Pulseras "Perla & Oro"',
    description: 'Elegante combinación de perlas y detalles dorados. Perfectas para cualquier ocasión, de día o de noche.',
    price: 49.9,
    originalPrice: 85.0,
    category: 'Accesorios',
    keywords: 'pulseras, perlas, oro, accesorios',
    imageId: 'product-8',
  },
  {
    id: '6',
    name: 'Aretes "Destello"',
    description: 'Pequeños pero brillantes, estos aretes son el toque final perfecto para tu atuendo. Ligeros y cómodos.',
    price: 35.9,
    originalPrice: 60.0,
    category: 'Accesorios',
    keywords: 'aretes, pendientes, destello, accesorios',
    imageId: 'product-9',
  },
];